version: '3.8'

services:
  chatappbd:
    container_name: ${MONGO_DB_NAME}
    image: mongo:7.0.5-rc0-jammy
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    command: ['--auth']

  mongo-express:
    depends_on:
      - chatappbd
    image: mongo-express:1.0.0-18-alpine3.17
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
      - ME_CONFIG_MONGODB_URL=${MONGO_URL} 
    ports:
      - 8081:8081
    restart: always

volumes:
  chatapp-vol:
    external: false